import type { Metadata } from "next";
import { Inter,IBM_Plex_Mono } from "next/font/google";
import { Providers } from "@/components/providers";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const plexMono = IBM_Plex_Mono({
  variable: "--font-plex-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${plexMono.variable} antialiased`}
      >
            <Providers>
                {children}
            </Providers>
        </body>
      </html>
  );
}


{/* <header className="flex justify-end items-center p-4 gap-4 h-16">
<SignedOut>
  <SignInButton />
  <SignUpButton>
    <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
      Sign Up
    </button>
  </SignUpButton>
</SignedOut>
<SignedIn>
  <UserButton />
</SignedIn>
</header> */}